version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mlops-api
    ports:
      - "8000:8000"
    networks:
      - mlops-network

  frontend:
    build: ./frontend
    container_name: mlops-pwa
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
    